steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--tag', '$_TAG',
      '--build-arg', 'NEXT_PUBLIC_API_BASE_URL=$_NEXT_PUBLIC_API_BASE_URL',
      '.'
    ]
images:
  - '$_TAG'
