"""add theme column to presentations

Revision ID: 82abdbc476a7
Revises: f42ad4074449
Create Date: 2026-03-24 12:42:46.220359

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "82abdbc476a7"
down_revision: str | None = "f42ad4074449"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
